--=======================================================================================
-- Generated by TypescriptToLua transpiler https://github.com/Perryvw/TypescriptToLua 
-- Date: Mon Jan 29 2018
--=======================================================================================
local a = ""
local b = {1,2,3}
local c = {d=a,e=b}
local d = #b
local e = #a
local f = #c.d
local g = #c.e
local h = #"abc"
table.insert(b, 3)
string.sub(a,"a","b")
